bindPort = 27000
auth.token = "xF5kJa#v"

# vhostHTTPPort = 80
vhostHTTPSPort = 443
subdomainHost = "yesky.online"

transport.tls.force = true
transport.tls.certFile = "/root/frp_0.54.0_linux_amd64/fullchain.pem"
transport.tls.keyFile = "/root/frp_0.54.0_linux_amd64/privkey.pem"

custom404Page = "/root/frp_0.54.0_linux_amd64/404.html"

# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer.addr = "0.0.0.0"
webServer.port = 27500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "Bilt8"

[log]
# 指定日志文件路径
to = "/var/log/frps.log" 

# 设置日志级别，可选值: trace, debug, info, warn, error
level = "info"

# 日志文件最大保留天数
maxDays = 14